### ISSUE TITLE
find bug in demo.py

### ISSUE THREAD

**Issue by Zyber404** [icbcbicc/FocusLiteNN#2]
in demo.py get_patches() line 31, 32
`h_start = np.arange(0, h - new_h, stride_h)
    w_start = np.arange(0, w - new_w, stride_w)`
should be 
`h_start = np.arange(0, h - new_h + 1, stride_h)
    w_start = np.arange(0, w - new_w + 1, stride_w)`
this will avoid a bug when h - new_h(w - new_w) % stride_h(stride_w) = 0

**Comment by icbcbicc** [comment]
> in demo.py get_patches() line 31, 32 `h_start = np.arange(0, h - new_h, stride_h) w_start = np.arange(0, w - new_w, stride_w)` should be `h_start = np.arange(0, h - new_h + 1, stride_h) w_start = np.arange(0, w - new_w + 1, stride_w)` this will avoid a bug when h - new_h(w - new_w) % stride_h(stride_w) = 0

Thanks. I've updated the code.
